# Generated by Django 5.0.11 on 2025-01-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentik_core", "0042_authenticatedsession_authentik_c_expires_08251d_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupTelegramSourceConnection",
            fields=[
                (
                    "groupsourceconnection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.groupsourceconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Telegram Source Connection",
                "verbose_name_plural": "Group Telegram Source Connections",
            },
            bases=("authentik_core.groupsourceconnection",),
        ),
        migrations.CreateModel(
            name="TelegramSource",
            fields=[
                (
                    "source_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.source",
                    ),
                ),
                (
                    "bot_id",
                    models.TextField(
                        default=False, help_text="Telegram bot id can be obtained from telegram API"
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Source",
                "verbose_name_plural": "Telegram Sources",
            },
            bases=("authentik_core.source",),
        ),
        migrations.CreateModel(
            name="TelegramSourcePropertyMapping",
            fields=[
                (
                    "propertymapping_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.propertymapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Source Property Mapping",
                "verbose_name_plural": "Telegram Source Property Mappings",
            },
            bases=("authentik_core.propertymapping",),
        ),
        migrations.CreateModel(
            name="UserTelegramSourceConnection",
            fields=[
                (
                    "usersourceconnection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.usersourceconnection",
                    ),
                ),
                ("identifier", models.TextField()),
            ],
            options={
                "verbose_name": "User Telegram Source Connection",
                "verbose_name_plural": "User Telegram Source Connections",
            },
            bases=("authentik_core.usersourceconnection",),
        ),
    ]
