# Generated by Django 5.0.11 on 2025-01-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_sources_telegram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramsource",
            name="bot_token",
            field=models.TextField(
                default=False, help_text="Telegram bot token can be obtained from BotFather"
            ),
        ),
    ]
